### ISSUE TITLE
V8 Engine error depends on Node.js version

### ISSUE THREAD

**Issue by oxmie** [social-dist0rtion-protocol/thc#7]
The latest commit [0420e05](https://github.com/social-dist0rtion-protocol/thc/commit/0420e057f63cc5fd70f2ea06cb1c64c77c8f4c91) of `thc` is not working with the latest version of Node.js (13.9.0)

It seems to have issues with the V8 engine and some changes there:

```bash
~/thc/eth (git master) # npm version
{
  eth: '1.0.0',
  npm: '6.13.7',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '36.0',
  icu: '65.1',
  llhttp: '2.0.4',
  modules: '79',
  napi: '5',
  nghttp2: '1.40.0',
  node: '13.9.0',
  openssl: '1.1.1d',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.34.2',
  v8: '7.9.317.25-node.28',
  zlib: '1.2.11'
}

~/thc/eth (git master) # g++ --version
g++ (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)
```
Error message:
```bash
~/thc/eth (git master) # npm install
...

../src/addon.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE KeccakWrapper::Initialize(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/addon.cc:37:47: error: no matching function for call to ‘v8::Value::IntegerValue()’
   37 |     unsigned int rate = info[0]->IntegerValue();
      |                                               ^
In file included from /home/user/.cache/node-gyp/13.9.0/include/node/node.h:67,
                 from ../src/addon.cc:1:

...

/home/user/.cache/node-gyp/13.9.0/include/node/v8.h:2774:40: note:   candidate expects 1 argument, 0 provided
../src/addon.cc:38:51: error: no matching function for call to ‘v8::Value::IntegerValue()’
   38 |     unsigned int capacity = info[1]->IntegerValue();
      |                                                   ^
In file included from /home/user/.cache/node-gyp/13.9.0/include/node/node.h:67,
                 from ../src/addon.cc:1:

...

/home/user/.cache/node-gyp/13.9.0/include/node/v8.h:2774:40: note:   candidate expects 1 argument, 0 provided
../src/addon.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE KeccakWrapper::Copy(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/addon.cc:75:82: error: no matching function for call to ‘v8::Value::ToObject()’
   75 |     KeccakWrapper* to = Nan::ObjectWrap::Unwrap<KeccakWrapper>(info[0]->ToObject());
      |                                                                                  ^
In file included from /home/user/.cache/node-gyp/13.9.0/include/node/node.h:67,
                 from ../src/addon.cc:1:
...

make: *** [keccak.target.mk:129: Release/obj.target/keccak/src/addon.o] Error 1
make: Leaving directory '/home/user/thc/eth/node_modules/keccak/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v13.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.100-1.pvops.qubes.x86_64
gyp ERR! command "/home/user/.nvm/versions/node/v13.9.0/bin/node" "/home/user/.nvm/versions/node/v13.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/thc/eth/node_modules/keccak
gyp ERR! node -v v13.9.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-02-29T14_51_35_810Z-debug.log

...

../src/addon.cpp:49:23: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
../src/addon.cpp:49:23: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
../src/addon.cpp: In static member function ‘static void SHA3Hash::Init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/addon.cpp:83:27: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>&, v8::Local<v8::Function>&)’
   83 |   target->Set(className, f);
      |                           ^
In file included from /home/user/.cache/node-gyp/13.9.0/include/node/node.h:67,
                 from ../src/addon.cpp:1:

...

make: *** [sha3.target.mk:115: Release/obj.target/sha3/src/addon.o] Error 1
make: Leaving directory '/home/user/thc/eth/node_modules/sha3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v13.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.100-1.pvops.qubes.x86_64
gyp ERR! command "/home/user/.nvm/versions/node/v13.9.0/bin/node" "/home/user/.nvm/versions/node/v13.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/thc/eth/node_modules/sha3
gyp ERR! node -v v13.9.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok 
npm WARN eth@1.0.0 No description
npm WARN eth@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-02-29T14_51_48_324Z-debug.log
```

I used [nvm](https://github.com/nvm-sh/nvm) (`nvm install node`)  to get Node.js

**Comment by o8F0LY** [comment]
Compiling `thc` work for me with `nvm install 12` (`node: '12.16.1',  v8: '7.8.279.23-node.31'`), but if you want to use [ethnode](https://github.com/vrde/ethnode/) as Ethereum node, you even has to take `nvm install 11` (`node: '11.15.0',  v8: '7.0.276.38-node.19'`), because `ethnode` cannot be compiled, because of same V8 engine errors.
```bash
...

../src/node-boilerplate/inc/scrypt_common.h:39:63: error: no matching function for call to ‘v8::Value::Uint32Value()’
   39 |       N(obj->Get(Nan::New("N").ToLocalChecked())->Uint32Value()),
      |                                                               ^
In file included from /home/user/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:

...
```

**Comment by vrde** [comment]
Sorry for not following up. We changed a lot of things and I assume this issue is not valid anymore. If you still have troubles please open a new issue.
